CITIES = [
    "Berlin",
    "Munich",
    "Hamburg",
    "Cologne",
    "Frankfurt am Main",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bonn",
    "Karlsruhe",
    "Mannheim",
]
